dist: trusty
sudo: required
servies:
  - docker

before_install:
  - docker pull zavorka/debian-gcc

script:
  - |
    COMMAND=$(cat <<-EOF
    set -e
    mkdir -p /src/build && cd /src/build
    cmake -DCMAKE_BUILD_TYPE=Debug ..
    cmake --build . --target self_test
    ./self_test
    EOF
    )
  - docker run --rm -v ${PWD}:/src zavorka/debian-gcc /bin/bash -c "$COMMAND"
