dist: trusty
sudo: require
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake


script: 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - gcc -v && g++ -v && cmake --version
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --target self_test
